# course: educative.io
def operators_example():
    print("List of all supported operators: Mathematical, Logical, Binary, Comparison")
    print("+ += operator")
    print("- -= operator")
    print("* *= operator")
    print(f"** **= operator,eg: 2 ** 3 = {format(2 ** 3)}")
    print(f"/ /= operator, floating point eg: 4 // 5 = {format(4/5)}")
    print(f"// //= operator, integer eg: 4 / 5 = {format(4//5)}")
    print(f"% %= modulo, eg: 5 % 3 = {format(5 % 3)}")
    print('"and" => "&&"')
    print('"or" => "||"')
    print('"not" => "~"')
    print(f"|, binary OR operation, eg {format(bin(2))} | {format(bin(3))}: ", bin(2 | 3))
    print(f"&, binary AND operation, eg {format(bin(2))} & {format(bin(3))}: ", bin(2 & 3))
    print(f"~, binary NOT operation, eg ~1 ~{format(bin(1))}: ", bin(~1), hex(~1))
    print("Above output is 0x1: 0001 converted to 1's complement and shown numerically, sign extended ")
    print(">, is 5 > 6", (5 > 6))
    print("<, is 5 < 6", (5 < 6))
    print("<=, is 3 <= 6", (3 <= 6))
    print(">=, is 6 >= 6", (6 >= 6))
    print("!= nd ==")
